name: PrismChatColor
version: '1.0.1'
main: dev.tunahanxx.PrismChatColor
api-version: '1.20'
authors: [ TunahanXX ]
description: PrismChatColor Plugin

commands:
  prismchatcolor:
    usage: /prismchatcolor help
  chatcolor:
    usage: /chatcolor
  cc:
    usage: /cc

permissions:
  prismchatcolor.*:
    description: All Permissions
    default: op
    children:
      prismchatcolor.chatcolor: true
      prismchatcolor.admin: true
      prismchatcolor.chatcolor-one: true
      prismchatcolor.chatcolor-second: true
      prismchatcolor.chatcolor-three: true
      prismchatcolor.chatcolor-four: true
      prismchatcolor.chatcolor-five: true
      prismchatcolor.chatcolor-six: true
      prismchatcolor.chatcolor-seven: true
      prismchatcolor.chatcolor-eight: true
      prismchatcolor.chatcolor-nine: true